repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports]
        types_or: [python, pyi]
        additional_dependencies:
        -   "sqlmodel==0.0.22"
