# .github/workflows/ruff.yml

name: Lint with Ruff

on:
  push:
    branches:
      - main
      - feature/pytest
  pull_request:

jobs:
  backend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Specify the Python version

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check backend  # Lint the entire repository
      
      - name: Run Ruff
        run: ruff check backend  # Lint the entire repository
  backend-test:
    runs-on: ubuntu-latest
    services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres
          # Provide the password for postgres
          env:
            POSTGRES_PASSWORD: postgres
          # Set health checks to wait until postgres has started
          ports:
          - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v4
      - name: Install dependencies
        working-directory: backend
        run: rye sync
      - name: Run tests
        working-directory: backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
        run: rye test
  frontend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"  # Specify Node.js version

      - name: Install dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        working-directory: frontend
        run: npx eslint .  # Runs ESLint on the frontend folder
